"""primera migracion

Revision ID: 6b41e9d7809f
Revises: 
Create Date: 2025-04-08 00:48:28.504305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b41e9d7809f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_email'), 'author', ['email'], unique=True)
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_index(op.f('ix_author_email'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
